---
title: "Intro to R programming"
---

## Topics

1.  R objects
2.  R packages
3.  Reading data in R
4.  Basic data wrangling

<a href="https://econ147-special-topic.github.io/econ147-lecture/module-intro-r" target="_blank" class="btn-slides">View slides in new window</a>

::: {.box style="padding-bottom:56.25%; position:relative; display:block; width: 100%"}
<iframe width="100%" height="100%" src="https://econ147-special-topic.github.io/econ147-lecture/module-intro-r" frameborder="0" allowfullscreen style="position:absolute; top:0; left: 0">

</iframe>
:::

::: callout-tip
## Presentation keyboard shortcuts

::: text-line-space
<ul>

<li>Use <kbd>←</kbd> and <kbd>→</kbd> to navigate through the slides</li>

<li>Use <kbd>F</kbd> to toggle full screen</li>

<li>Use <kbd>O</kbd> to view an overview of all slides</li>

<li>Use <kbd>?</kbd> to see a list of other shortcuts</li>

</ul>
:::
:::

<br>

## Exercises

1. Install [R](https://cran.r-project.org/bin/windows/base/) and [RStudio](https://posit.co/download/rstudio-desktop/) on your computer.

2. Download the entire folder `00-module-intro-r` from the [Google Drive link](https://drive.google.com/drive/folders/1GEK546pk2n07ji4TuafoyzK-eXTFgjn2?usp=sharing). For the meantime, keep the folder in your computer and wait for further instructions during the class.

3. Before the class start, open the RStudio and paste the following code in the console to install the required packages. Just click the clipboard icon to copy the code.

```{r}
#| eval: false

## install required packages
install.packages(c("janitor", "readxl", "haven", "tidyverse", "skimr"))
```


:::{.callout-warning}
## Important

Please make sure to install the required packages before the class starts, as we may not have a secure internet connection. If you encounter any issues, please let me know.

:::


## Class demonstration in progress

```{.r}
# INTRO TO R AND BASIC DATA WRANGLING ----

## Install packages
# install.packages("readr")
# install.packages(c("janitor", "readxl", "haven", "tidyverse", "skimr"))


# 1. R Packages ----
library(readr) # reading csv files librar
library(readxl) # reading excel files
library(haven) # reading spss, sas, stata files
library(tidyverse) # load all packages under tidyverse environment
library(dplyr) # for data wrangling
library(skimr) # quick exploration of your data
library(janitor) # quick cleaning of dataset


# 2. Set the working directory ----
setwd("D:/Githu-repository/econ147-special-topic-bcon/econ147-class-exercise-demo/class-demo-exercise/00-module-intro-r")


# 3. Reading data into R ----

## 3.1 CSV files
### Load swimming_pools.csv files using the read_csv() function
swimming_data <- read_csv("sample_dataset/swimming_pools.csv") 


### Load potatoes.csv using read_csv() and read.csv()
#### Observe the difference in the output
potatoes_data <- read_csv("sample_dataset/potatoes.csv") 



## 3.2 Excel files
### Load urban_pop files and use the read_xls() and read_excel() functions
### Save the data into a variable named urban_pop

```


