project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Bcon 147"
  favicon: "plot/Bcon147-hex-logo.png"
  
  repo-url: https://github.com/econ147-special-topic/econ147-site
  site-url: https://econ147-special-topic/econ147-site
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/Bcon147-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "00-m0-intro-r.qmd"
            text: "Introduction to R programming"
          - href: "00-m0-intro-data-viz-ggplot.qmd"
            text: "Intro to data visualization using ggplot2"


format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual